spring:
  application:
    name: product-service
  cloud:
    config:
      profile: prod
  loadbalancer:
    ribbon:
      enabled: false
    cache:
      enabled: true
      ttl: 30s
  datasource:
    url: jdbc:mysql://localhost:3306/retail?useSSL=false # localhost:puerto/DBNAME?useSSL=false / no usamos SSL
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 3
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: retailnosql
redis:
  host: localhost
  port: 6379
  password:
  timeout: 2s                 # Timeout en segundos (s)
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
  #time-to-live: 1m            # Tiempo de vida del cache

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3         # intenta hasta 3 veces
        waitDuration: 5s       # espera 2 s entre cada intento
    instances:
      productService:
        baseConfig: default
        waitDuration: 10s
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED  # Medición por conteo
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        #permittedNumberOfCallsInHalfOpenState: 5
    instances:
      customerService:
        baseConfig: default
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
      dataBase:
        baseConfig: default
        waitDurationInOpenState: 30s


# OpenAPI/Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs


server:
  #port: 0
  port: 9092
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.int(10000,99999)}-${spring.application.instance_id:${random.value}}
    #instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: INFO
    com.mitocode.product_service: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.openfeign: DEBUG