spring:
  application:
    name: product-service
  cloud:
    config:
      profile: prod
  loadbalancer:
    ribbon:
      enabled: false
    cache:
      enabled: true
      ttl: 30s

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.int(1000,9999)}
    #hostname: host.docker.internal
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
