spring:
  application:
    name: product-service
  cloud:
    config:
      profile: dev

product:
  user: usuarioTest
  pass: claveTest

eureka:
  instance:
    prefer-ip-address: false
    hostname: host.docker.internal
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

